### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by TeTarakona** [TeTarakona/Capstone-Assistant#6]
## Description

Create the todo list portion of the application.

## Acceptance Criteria

- [x] A list item can be created, read, updated, or deleted via the React application.
- [x] The Express server is able to handle the request given by the React application and handle it appropriately. Including fail-cases.
- [x] The Express server is able to manipulate the database appropriately in response to the request from the React application.
